<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9593aafcccc0899224c5751d04906a16
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'AfterShip\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'AfterShip\\' => 
        array (
            0 => __DIR__ . '/..' . '/aftership/aftership-php-sdk/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9593aafcccc0899224c5751d04906a16::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9593aafcccc0899224c5751d04906a16::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
